In [24]:
# import libraries
import pandas as pd;

In [25]:
# read CSVs
financials_2018 = pd.read_csv('../data/2018_Financial_Data.csv');

In [26]:
# print all industries available
financials_2018.Sector.unique()

array(['Consumer Cyclical', 'Energy', 'Technology', 'Industrials',
       'Financial Services', 'Basic Materials', 'Communication Services',
       'Consumer Defensive', 'Healthcare', 'Real Estate', 'Utilities'],
      dtype=object)

In [18]:
# clean up data
# we only want companies from the consumer packaged goods industry, "Consumer Cyclical".
# we can consider "Consumer Defensive" as well?
consumer_2018 = financials_2018.loc[financials_2018['Sector'] == "Consumer Cyclical"];

In [30]:
# add name for ticker column
consumer_2018.rename(columns={consumer_2018.columns[0]: "Ticker"}, inplace=True)

c:\users\trieu\appdata\local\programs\python\python38\lib\site-packages\pandas\core\frame.py:4296: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [20]:
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)

In [5]:
# Remove specific keywords.
# Not used anymore, was used to isolate attributes.

#financials_2018_cols = [c for c in financials_2018.columns if c.lower()[-5:] != 'ratio']
#financials_2018_cols = [c for c in financials_2018_cols if c.lower()[-6:] != 'ratios']
financials_2018_cols = [c for c in financials_2018.columns if c.lower()[-6:] != 'margin']
financials_2018_cols = [c for c in financials_2018_cols if c.lower()[-8:] != 'turnover']
financials_2018_cols = [c for c in financials_2018_cols if c.lower()[-6:] != 'growth']
financials_2018_cols = [c for c in financials_2018_cols if c.lower()[-18:] != 'growth (per share)']
financials_2018_cols = [c for c in financials_2018_cols if c.lower()[-9:] != 'per share']
financials_2018_cols = [c for c in financials_2018_cols if c.lower()[-8:] != 'pershare']

In [32]:
# Select specific attributes from the consumer dataset
consumer_2018 = consumer_2018[['Ticker',
                               'Revenue',
                               'Cost of Revenue',
                               'Gross Profit',
                               'R&D Expenses',
                               'SG&A Expense',
                               'Operating Expenses',
                               'Operating Income',
                               'Interest Expense',
                               'Earnings before Tax',
                               'Income Tax Expense',
                               'Net Income',
                               'Preferred Dividends',
                               'Net Income Com',
                               'EBITDA',
                               'EBIT',
                               'Consolidated Income',
                               'Cash and cash equivalents',
                               'Short-term investments',
                               'Cash and short-term investments',
                               'Receivables',
                               'Inventories',
                               'Total current assets',
                               'Property, Plant & Equipment Net',
                               'Goodwill and Intangible Assets',
                               'Long-term investments',
                               'Tax assets',
                               'Total non-current assets',
                               'Total assets',
                               'Payables',
                               'Short-term debt',
                               'Total current liabilities',
                               'Long-term debt',
                               'Total debt',
                               'Deferred revenue',
                               'Tax Liabilities',
                               'Deposit Liabilities',
                               'Total non-current liabilities',
                               'Total liabilities',
                               'Other comprehensive income',
                               'Retained earnings (deficit)',
                               'Total shareholders equity',
                               'Investments',
                               'Net Debt',
                               'Other Assets',
                               'Other Liabilities',
                               'Depreciation & Amortization',
                               'Stock-based compensation',
                               'Operating Cash Flow',
                               'Capital Expenditure',
                               'Acquisitions and disposals',
                               'Investment purchases and sales',
                               'Investing Cash flow',
                               'Issuance (repayment) of debt',
                               'Issuance (buybacks) of shares',
                               'Dividend payments',
                               'Financing Cash Flow',
                               'Free Cash Flow',
                               'Market Cap',
                               'Enterprise Value',
                               'Working Capital',
                               '2019 PRICE VAR [%]',
                               'Class']]

In [41]:
# Shows the rows that contain at least one nan
consumer_2018_nan_rows = consumer_2018[consumer_2018.isna().any(axis=1)]

In [42]:
# Shows the number of nans in each column
consumer_2018.isnull().sum().sort_values()

Total current liabilities           0
Financing Cash Flow                 0
Investing Cash flow                 0
Capital Expenditure                 0
Operating Cash Flow                 0
Total shareholders equity           0
Total liabilities                   0
Long-term debt                      0
2019 PRICE VAR [%]                  0
Payables                            0
Total assets                        0
Total current assets                0
Receivables                         0
Cash and cash equivalents           0
Class                               0
Operating Income                    0
Gross Profit                        0
Income Tax Expense                  2
Depreciation & Amortization         2
Property, Plant & Equipment Net     2
SG&A Expense                        2
Revenue                             2
Net Income Com                      2
Long-term investments               4
Cost of Revenue                     4
Earnings before Tax                 4
Retained earnings (deficit)         4
Goodwill and Intangible Assets      6
EBIT                                6
Operating Expenses                  6
Total debt                          6
Other Liabilities                   7
Free Cash Flow                      7
Other Assets                        7
Investment purchases and sales      7
Stock-based compensation            7
Other comprehensive income          7
Tax Liabilities                     7
Deferred revenue                    7
Interest Expense                    7
Cash and short-term investments     7
Consolidated Income                 8
Investments                         8
Short-term debt                     8
Net Income                          8
EBITDA                              8
Issuance (repayment) of debt        8
Issuance (buybacks) of shares      10
Inventories                        10
Tax assets                         11
Short-term investments             12
Net Debt                           14
Acquisitions and disposals         15
Dividend payments                  17
Deposit Liabilities                17
Preferred Dividends                18
R&D Expenses                       19
Total non-current assets           32
Total non-current liabilities      33
Market Cap                         34
Working Capital                    45
Enterprise Value                   65
dtype: int64

In [47]:
# Drops the nan rows from the dataset
consumer_2018 = consumer_2018.dropna()

In [35]:
consumer_2018

,Ticker,Revenue,Cost of Revenue,Gross Profit,R&D Expenses,...,Market Cap,Enterprise Value,Working Capital,2019 PRICE VAR [%],Class
0,CMCSA,9.450700e+10,0.000000e+00,9.450700e+10,0.0,...,1.549106e+11,2.628396e+11,-5.755000e+09,32.794573,1
8,SIRI,5.770692e+09,2.308606e+09,3.462086e+09,123219000.0,...,2.536181e+10,3.219581e+10,-2.325000e+09,22.161943,1
11,CZR,8.391000e+09,4.181000e+09,4.210000e+09,0.0,...,4.547487e+09,2.193249e+10,2.650000e+08,96.531795,1
12,F,1.603380e+11,1.457320e+11,1.460600e+10,0.0,...,3.043096e+10,1.506930e+11,1.908000e+10,25.537204,1
25,NKE,3.639700e+10,2.044100e+10,1.595600e+10,0.0,...,1.157243e+11,1.142893e+11,9.094000e+09,38.243248,1
...,...,...,...,...,...,...,...,...,...,...,...
4353,UONE,4.390980e+08,1.253640e+08,3.137340e+08,0.0,...,9.823137e+07,9.948044e+08,6.192100e+07,-3.809520,0
4354,UONEK,4.390980e+08,8.114600e+07,2.805450e+08,NaN,...,NaN,NaN,NaN,4.395600,1
4362,VNCE,2.725820e+08,1.507930e+08,1.217890e+08,0.0,...,8.758343e+07,1.308934e+08,3.639700e+07,69.539661,1
4375,WINA,7.251110e+07,4.670400e+06,6.784070e+07,0.0,...,6.202911e+08,6.280086e+08,1.176800e+07,26.169646,1
4385,XELB,3.546600e+07,2.702000e+06,3.276400e+07,0.0,...,2.066153e+07,3.139953e+07,7.759000e+06,27.118650,1